site_name: booking
site_description: Headless Booking API with DRF.
repo_url: https://github.com/kavinjey/booking-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/kavinjey">kavinjey</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
